name: Build and Publish Metahack APT Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Build Metahack .deb package
        run: |
          mkdir -p metahack/DEBIAN
          echo "Package: metahack" > metahack/DEBIAN/control
          echo "Version: 1.0" >> metahack/DEBIAN/control
          echo "Architecture: all" >> metahack/DEBIAN/control
          echo "Maintainer: HYDRA-TERMUX" >> metahack/DEBIAN/control
          echo "Description: Metahack - Metasploit Automation Tool" >> metahack/DEBIAN/control
          
          mkdir -p metahack/usr/bin
          
          # Check if metarun.sh exists before copying
          if [ -f metarun.sh ]; then
            cp metarun.sh metahack/usr/bin/metahack
            chmod +x metahack/usr/bin/metahack
          else
            echo "Error: metarun.sh not found!" >&2
            exit 1
          fi
          
          dpkg-deb --build metahack metahack.deb

      - name: Setup APT Repository
        run: |
          mkdir -p repo
          mv metahack.deb repo/
          cd repo
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./repo
