name: Build and Publish Metahack APT Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Set Up APT Repo Directory
        run: |
          mkdir -p repo/DEBIAN
          echo "Package: metahack" > repo/DEBIAN/control
          echo "Version: 1.0" >> repo/DEBIAN/control
          echo "Architecture: all" >> repo/DEBIAN/control
          echo "Maintainer: HYDRA-TERMUX" >> repo/DEBIAN/control
          echo "Description: Metahack APT package" >> repo/DEBIAN/control
          
      - name: 📦 Build .deb Package
        run: |
          dpkg-deb --build repo metahack.deb
          mkdir -p public
          mv metahack.deb public/

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: ./public
